baseURL = 'https://mopp.jp/'
languageCode = 'ja'
title = 'moppris'

enableEmoji = true
hasCJKLanguage = true

disableKinds = ['page', 'section', 'taxonomy', 'term', 'sitemap']

copyright = "&copy;2016-2023 Copyright mopp, All Rights Reserved."

[outputs]
  home = ['HTML']

[minify]
  disableXML = true

[params]
  author = 'mopp'
  description = "About mopp."
